// Top-level build file. Plugin versions live in gradle/libs.versions.toml.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.binary.compatibility.validator)
}

// The public API is a permanent compatibility commitment. `apiCheck` fails the build
// when it changes without `apiDump` being re-run and the diff reviewed, so the surface
// cannot drift silently — the iOS SDK had to demote 109 accidentally-public
// declarations before 1.0 froze them.
apiValidation {
    // The sample app is an app, not a published artifact.
    ignoredProjects.add("sample-app")
    // Generated by AGP, not part of the API we commit to.
    ignoredClasses.add("com.uqpay.sdk.BuildConfig")
}
