// Top-level build file. Plugin versions live in gradle/libs.versions.toml.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.binary.compatibility.validator)
}

// The public API is a permanent compatibility commitment. `apiCheck` fails the build
// when it changes without `apiDump` being re-run and the diff reviewed, so the surface
// cannot drift silently — the iOS SDK had to demote 109 accidentally-public
// declarations before 1.0 froze them.
apiValidation {
    // The sample app is an app, not a published artifact.
    ignoredProjects.add("sample-app")
    // Generated by AGP, not part of the API we commit to.
    ignoredClasses.add("com.uqpay.sdk.BuildConfig")
    // Generated by the Compose compiler, which hoists every non-capturing composable lambda
    // in a file into one holder class. The holder's own members are internal — the compiler
    // mangles them with `$uqpay_sdk_release`, so no merchant can call them — but the class
    // it puts them in is emitted public and there is no way to ask the compiler for
    // otherwise. Same category as BuildConfig above: compiler output, not a commitment.
    // Named per file so a *new* Compose file cannot slip its own holder in unnoticed.
    ignoredClasses.add("com.uqpay.sdk.ui.ComposableSingletons\$PaymentScreenKt")
}

// The Compose compiler stamps a `public static final int $stable` field on every public
// and internal class it compiles — a stability hint for the Compose runtime, not part of
// any API we offer, and BCV has no field-level filter for it. Strip those lines from
// the generated dump before `apiCheck`/`apiDump` see it, so the frozen file records only
// declarations we actually commit to. Anything else Compose adds still fails the check.
subprojects {
    tasks.matching { it.name == "apiBuild" }.configureEach {
        doLast {
            outputs.files.asFileTree.matching { include("**/*.api") }.forEach { dump ->
                val kept = dump.readLines().filterNot { it.trim() == "public static final field \$stable I" }
                dump.writeText(kept.joinToString("\n", postfix = "\n"))
            }
        }
    }
}
